In [8]:
#ABC's
import numpy as np

x = ["a","b","c","d","e","f","g","h","i","j"]
y=np.array(x)
y

#dtype of array
y.dtype
print("the elements in y are of type:", y.dtype)

#shape of array
y.shape
print("y has dimensions: ",y.shape)

#size of array
y.size

the elements in y are of type: <U1
y has dimensions:  (10,)


10

In [22]:
#Create an ndarray
x = np.arange(2,33,2)
print("x =",x)
print("The elements in x are" ,x.size)

x = np.reshape(x,(4,4))
print("Reshaped X= \n",x)
print("The elements in x are" ,x.size)
print("X has dimensions:", x.shape)

x = np.arange(2,33,2).reshape(4,4)
print("x =",x)

#creating the same array using the np.linspace()
x = np.linspace(2,32,16)
print("X = \n",x)
print("The elements in x are" ,x.size)


x = [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]
The elements in x are 16
Reshaped X= 
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
The elements in x are 16
X has dimensions: (4, 4)
x = [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
X = 
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
The elements in x are 16


In [44]:
#Manipulating ndarrays
z = np.arange(1,26).reshape(5,5)
print("z =",z)

odd_numbers = z[z % 2 != 0]

print(odd_numbers)


z = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
